services:
  - type: web
    name: youtube-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        value: 27775431
      - key: API_HASH
        value: b70bb1d45a1d05236671d4cc615e40f9
      - key: BOT_TOKEN
        value: b70bb1d45a1d05236671d4cc615e40f9